### ISSUE TITLE
Add one o more Tags for register

### ISSUE THREAD

**Issue by guirahy** [fabiorogeriosj/timet#8]
Add one o more Tags in register for account by Tags in reports, like this:
timet 35m Checked infra of deploy @projet1 @work
timet 2h Develop feature xyz @projet2 @freela

And option to list by Tags, like this:
timet 2/20/2017 3/20/2017 @work
timet 2/20/2017 3/20/2017 @project1 --report

**Comment by brunopenso** [comment]
I have the same idea here!

**Comment by fabiorogeriosj** [comment]
Implemented in https://github.com/fabiorogeriosj/timet/pull/9
